name: aura
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase and Google Maps
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  google_maps_flutter: ^2.6.1
  
  # Utility Packages
  geolocator: ^12.0.0
  intl: ^0.19.0
  fl_chart: ^0.68.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets for the custom map style
  assets:
    - assets/
