// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvV3dyiZ18SKuHWSrP7u-7rM2cIWR7liE',
    appId: '1:893530427598:web:f90e213448332f201a409f',
    messagingSenderId: '893530427598',
    projectId: 'aura-project-8dc5b',
    authDomain: 'aura-project-8dc5b.firebaseapp.com',
    databaseURL: 'https://aura-project-8dc5b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-project-8dc5b.firebasestorage.app',
    measurementId: 'G-WQC65XKTLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhCzZlyJWqO6K3Wgb4xv35FB0mY0bPrZI',
    appId: '1:893530427598:android:304aa5f4ffc455a51a409f',
    messagingSenderId: '893530427598',
    projectId: 'aura-project-8dc5b',
    databaseURL: 'https://aura-project-8dc5b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-project-8dc5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvj4xJ2bX9ezOlUYL24jR4iqMSBw2oxho',
    appId: '1:893530427598:ios:a84537d6b8aa0f431a409f',
    messagingSenderId: '893530427598',
    projectId: 'aura-project-8dc5b',
    databaseURL: 'https://aura-project-8dc5b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-project-8dc5b.firebasestorage.app',
    iosBundleId: 'com.example.aura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvj4xJ2bX9ezOlUYL24jR4iqMSBw2oxho',
    appId: '1:893530427598:ios:a84537d6b8aa0f431a409f',
    messagingSenderId: '893530427598',
    projectId: 'aura-project-8dc5b',
    databaseURL: 'https://aura-project-8dc5b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-project-8dc5b.firebasestorage.app',
    iosBundleId: 'com.example.aura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvV3dyiZ18SKuHWSrP7u-7rM2cIWR7liE',
    appId: '1:893530427598:web:2fd334004970c31b1a409f',
    messagingSenderId: '893530427598',
    projectId: 'aura-project-8dc5b',
    authDomain: 'aura-project-8dc5b.firebaseapp.com',
    databaseURL: 'https://aura-project-8dc5b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aura-project-8dc5b.firebasestorage.app',
    measurementId: 'G-JRWQCX5CMH',
  );
}
